import { Code, Lightbulb, MessageSquare, Rocket, Server, Users } from "lucide-react";

export const exercices = [
  {
    numero: 1,
    titre: "Créer un nouveau projet Next.js",
    description: "Mettre en place le projet avec la configuration recommandée",
    icon: Rocket,
    color: "blue",
    details: [
      "Utiliser `create-next-app@latest` avec l'App Router",
      "Sélectionner TypeScript, Tailwind CSS, ESLint",
      "Installer les dépendances nécessaires",
    ],
  },
  {
    numero: 2,
    titre: "Page d'accueil en SSG",
    description: "Créer une page de présentation statique",
    icon: Code,
    color: "purple",
    details: [
      "Créer/modifier `app/page.tsx`",
      "Afficher une photo ou avatar",
      "Se présenter (nom, passions, compétences)",
      "Utiliser Server Component (pas de 'use client')",
      "Design avec Tailwind CSS",
    ],
  },
  {
    numero: 3,
    titre: "Page en SSR avec génération de contenu via Route Handler + AI SDK",
    description:
      "Apprendre à créer un Route Handler interne et une page SSR qui l'appelle",
    icon: Lightbulb,
    color: "amber",
    details: [
      "Créer `app/api/ai/route.ts` (Route Handler)",
      "Utiliser `generateText()` de l'AI SDK pour générer du texte",
      "Retourner un JSON avec `NextResponse.json()`",
      "Créer `app/idee/page.tsx` (ou autre nom) avec `export const dynamic = 'force-dynamic'`",
      "Appeler le Route Handler interne avec `fetch('/api/ai', { cache: 'no-store' })`",
      "Afficher le contenu généré par l'IA (citation, idée, fun fact, etc.)",
      "Comprendre : la clé API reste sécurisée côté serveur (jamais exposée au client)",
    ],
  },
  {
    numero: 4,
    titre: "Chatbot en CSR avec AI SDK",
    description: "Créer un chatbot interactif avec streaming",
    icon: MessageSquare,
    color: "blue",
    details: [
      "Installer `@ai-sdk/react` et `@ai-sdk/groq`",
      "Créer une clé API sur groq.com (gratuit)",
      "Créer `app/chat/page.tsx` avec `'use client'`",
      "Utiliser le hook `useChat()` pour gérer les messages",
      "Afficher les messages et le formulaire de chat",
      "Suivre la documentation : https://ai-sdk.dev/docs/getting-started/nextjs-app-router",
    ],
  },
  {
    numero: 5,
    titre: "Route Handler API pour le chatbot",
    description: "Créer l'endpoint API qui communique avec le LLM",
    icon: Server,
    color: "green",
    details: [
      "Créer `app/api/chat/route.ts`",
      "Implémenter une fonction `POST` async",
      "Utiliser `streamText()` de la lib `ai`",
      "Configurer le modèle Groq avec la clé API",
      "Retourner `result.toTextStreamResponse()` ou `result.toUIMessageStreamResponse()`",
      "Gérer les erreurs (clé API manquante, etc.)",
    ],
  },
  {
    numero: 6,
    titre: "Chat Collaboratif en Temps Réel avec WebSocket et IA",
    description: "Créer un chat multi-utilisateurs avec Socket.IO et intégration IA conditionnelle",
    icon: Users,
    color: "purple",
    details: [
      "Installer les dépendances : `socket.io`, `socket.io-client`, `dotenv`, `tsx`, `concurrently`",
      "Créer un serveur WebSocket standalone (`server.ts`) avec Socket.IO sur le port 3001",
      "Configurer le serveur pour charger les variables d'environnement avec dotenv",
      "Implémenter la gestion des connexions/déconnexions des utilisateurs",
      "Créer un système de pseudos uniques avec validation (max 20 caractères)",
      "Gérer l'historique des messages en mémoire (stockage temporaire)",
      "Implémenter le broadcast des messages à tous les clients connectés",
      "Détecter les mentions @chatbot avec une regex (case-insensitive)",
      "Intégrer l'IA (Groq avec Llama 3.3 70B) qui analyse les 5 derniers messages pour répondre",
      "Créer la page client (`app/collaborative-chat/page.tsx`) avec 'use client'",
      "Implémenter la connexion Socket.IO côté client avec gestion de l'état (connecté/déconnecté)",
      "Créer une page de connexion pour choisir un pseudo avant d'entrer dans le chat",
      "Afficher la liste des utilisateurs connectés en temps réel",
      "Implémenter l'affichage des messages avec distinction visuelle (utilisateurs vs IA)",
      "Ajouter un indicateur 'en train d'écrire...' avec les événements `user:typing` et `user:stop-typing`",
      "Implémenter l'auto-scroll vers les nouveaux messages avec useRef",
      "Créer un design responsive avec Tailwind (messages alignés, couleurs différentes pour l'IA)",
      "Ajouter les scripts npm dans `package.json` : `socket` et `dev:all` (avec concurrently)",
      "Tester avec plusieurs onglets/navigateurs en utilisant différents pseudos",
      "Vérifier que l'IA répond correctement quand on mentionne @chatbot dans un message",
    ],
  },
];
